### ISSUE TITLE
2. RESPONSIVE WEB

### ISSUE THREAD

**Issue by jechfernandez** [Adalab/project-promo-l-module-1-team5#53]
**VALUE**
Someone visiting our site could have a better experience regardless of the device

**CONTEXT**
Sophie is the owner of a software factory. She attended a technical event to recruit technical talent. She is looking for junior front-end developers to add to her team. At the event she mets one adalaber that shows her the website she made during the course. She saves the site to check it out in the office and she contacts the adalaber after the course in order to hire her.

**RESOURCES**
Images in different sizes

**Tasks**
 

- [x] Header - tablet version
- [x]  Hero - tablet version
- [x]  Who we are - tablet version
- [x]  Strengths and weaknesses - tablet version
- [x]  Adalabers cards - tablet version
- [x]  Footer - tablet version
- [x]  Header - desktop version
- [x]  Hero - desktop version
- [x]  Who we are - desktop version
- [x]  Strengths and weaknesses - desktop version
- [x]  Adalabers cards - desktop version
- [x]  Footer - desktop version
- [x]  Published online

**Files**
![image](https://user-images.githubusercontent.com/75788321/102411153-cf266400-3ff1-11eb-8764-b11b7677fd2a.png)
![image](https://user-images.githubusercontent.com/75788321/102411209-dea5ad00-3ff1-11eb-8a5c-1b962474a9c9.png)
